"""Content plan data for DREM Book, Oct 1 2026 to Dec 31 2027.

Edit topics here, then run build.py to regenerate the calendar spreadsheet
and the data behind the strategy page.

Each weekly slot item is (pillar, format, topic):
  pillars  L = Learn, B = Behind the book, C = Community, D = Dream, O = Offer
  formats  see FORMATS below
"""

PILLARS = {
    "L": "Learn",
    "B": "Behind the book",
    "C": "Community",
    "D": "Dream",
    "O": "Offer",
}

# format code -> (label, post type in the social post generator, or "" if filmed / native)
FORMATS = {
    "CAR": ("Carousel", "carousel"),
    "TIP": ("Tip graphic", "tip"),
    "SVC": ("Service graphic", "service"),
    "ANN": ("Announcement graphic", "announcement"),
    "QUO": ("Quote graphic", "quote"),
    "REEL": ("Short video (Reels / TikTok / Shorts)", ""),
    "POLL": ("Question or poll", ""),
    "PHOTO": ("Photo post", ""),
    "PROMO": ("Blog promo graphic", "announcement"),
}

PHASES = [
    {
        "id": 1, "name": "Launch & listen", "start": "2026-10-01", "end": "2026-12-31",
        "goal": "Introduce DREM Book, earn trust and start the email list.",
        "mix": {"L": 50, "C": 20, "D": 10, "B": 10, "O": 10},
        "focus": [
            "Introduce every service once, clearly and warmly.",
            "Launch the free Manuscript Readiness Checklist as the newsletter sign-up gift.",
            "Ask questions and reply to every comment to learn what authors need.",
            "Record baselines in the first 6 weeks: reach, saves, profile visits, sign-ups.",
        ],
        "targets": [
            "Newsletter live with a sign-up gift by Oct 1",
            "Every service introduced at least once",
            "Baselines recorded for each platform by mid-November",
            "First enquiries logged with where they came from",
        ],
    },
    {
        "id": 2, "name": "Grow & invite", "start": "2027-01-01", "end": "2027-06-30",
        "goal": "Grow the audience and invite authors to book discovery calls.",
        "mix": {"L": 50, "C": 20, "D": 10, "B": 5, "O": 15},
        "focus": [
            "Ride New Year goal-setting: help authors plan their 2027 book.",
            "Show the process: editorial letters, cover sketches, proof copies.",
            "Share client stories once authors give written permission.",
            "One clear offer each month, never more than one a week.",
        ],
        "targets": [
            "Newsletter growing every month",
            "Saves and shares rising on Learn posts (compared to phase 1 baselines)",
            "Discovery calls booked every month",
            "First client stories published, with permission",
        ],
    },
    {
        "id": 3, "name": "Convert & scale", "start": "2027-07-01", "end": "2027-12-31",
        "goal": "Turn the audience into booked projects, with seasonal campaigns.",
        "mix": {"L": 45, "C": 20, "D": 10, "B": 10, "O": 15},
        "focus": [
            "\"Publish before the holidays\" campaign with a real production deadline.",
            "Celebrate DREM Book's first year on Oct 1, 2027.",
            "Black Friday / Cyber Monday offer for 2028 booking slots.",
            "Year in review and 2028 planning content in December.",
        ],
        "targets": [
            "Holiday-launch projects booked before the production deadline",
            "Enquiries each month traced back to a post, blog or email",
            "Best-performing posts turned into evergreen repeats",
            "2028 strategy drafted from 15 months of results",
        ],
    },
]

# Month-by-month plan. Lists are used in date order; each needs at least as many
# entries as that weekday occurs in the month.
MONTHS = {
    "2026-10": {
        "theme": "Every book starts as a dream",
        "summary": "Launch month. Introduce DREM Book and each service, and open the newsletter.",
        "campaign": "Launch week (Oct 1–7) and the free Manuscript Readiness Checklist",
        "newsletter": "Welcome to DREM Book + your free Manuscript Readiness Checklist",
        "blogs": [
            ("How to know your manuscript is ready for an editor", "is my manuscript ready for an editor"),
            ("Developmental, line or copy editing: which one do you need?", "types of book editing"),
            ("Self-publishing vs traditional publishing: an honest comparison", "self-publishing vs traditional publishing"),
            ("How to prepare for a month of writing your novel in November", "novel writing month tips"),
            ("", ""),
        ],
        "mon": [
            ("L", "TIP", "3 signs your manuscript is ready for an editor (sample post 03)"),
            ("L", "CAR", "From first page to final print: the 5 steps (sample post 07)"),
            ("L", "CAR", "The 4 types of editing, one slide each"),
            ("L", "REEL", "What an ISBN is, in 30 seconds"),
            ("L", "TIP", "5 things to decide before you write chapter one"),
        ],
        "fri": [
            ("O", "SVC", "Editing: your story, sharpened (sample post 01)"),
            ("O", "SVC", "Cover design: readers do judge a book by its cover (sample post 02)"),
            ("O", "SVC", "Printing: hold your book in your hands (sample post 04)"),
            ("O", "SVC", "Ebook & audiobook: read it, swipe it, hear it (sample post 06)"),
            ("C", "POLL", "Halloween: what's the scariest thing about publishing? (typos, blank pages, launch day)"),
        ],
        "sun": [
            ("D", "QUO", "Maya Angelou: \"no greater agony than bearing an untold story\" (sample post 05)"),
            ("C", "POLL", "What's the book you've always wanted to write?"),
            ("C", "POLL", "Plotter or pantser? Tell us how you write"),
            ("C", "PHOTO", "Show us where you write (share your writing space)"),
            ("C", "POLL", "Which step of publishing feels most confusing?"),
        ],
    },
    "2026-11": {
        "theme": "Write the draft",
        "summary": "November novel-writing month. Keep writers going, then show what happens after the draft.",
        "campaign": "30-day writing challenge with weekly check-ins; Black Friday early booking for 2027",
        "newsletter": "Your November writing plan + a printable word-count tracker",
        "blogs": [
            ("How to write 50,000 words in a month without burning out", "how to write a novel in a month"),
            ("Writer's block: 7 practical ways to get unstuck", "how to overcome writer's block"),
            ("How to outline a novel (even if you hate outlining)", "how to outline a novel"),
            ("Finished your first draft? Here's what to do next", "what to do after finishing first draft"),
            ("", ""),
        ],
        "mon": [
            ("L", "TIP", "Daily word-count tracker for November (save this)"),
            ("L", "CAR", "5 prompts to restart a stalled scene"),
            ("L", "CAR", "Show, don't tell: 3 before-and-after examples"),
            ("L", "TIP", "How to write an opening line that hooks readers"),
            ("L", "REEL", "Draft done? Why you should rest it for 30 days"),
        ],
        "fri": [
            ("B", "REEL", "What happens on your first call with DREM Book"),
            ("B", "PHOTO", "Meet the team: introduce one editor or designer (photo + favourite book)"),
            ("B", "CAR", "A sample edited page: before and after"),
            ("O", "ANN", "Black Friday: early booking for 2027 editing slots"),
            ("", "", ""),
        ],
        "sun": [
            ("C", "POLL", "National Authors' Day: tag an author who made you want to write"),
            ("C", "POLL", "What time of day do you write best?"),
            ("C", "POLL", "Share your word count this week (celebrate every number)"),
            ("D", "QUO", "Toni Morrison: \"If there's a book that you want to read, but it hasn't been written yet, then you must write it.\""),
            ("C", "PHOTO", "Thank you for your first two months with us"),
        ],
    },
    "2026-12": {
        "theme": "Plan your 2027 book",
        "summary": "Year-end reflection and planning. Help authors set a realistic 2027 publishing plan.",
        "campaign": "Book January slots; writer's gift guide",
        "newsletter": "Your 2027 book plan in 5 steps + January booking dates",
        "blogs": [
            ("How long does it take to self-publish a book? A realistic timeline", "how long does it take to self-publish a book"),
            ("What does it cost to self-publish a book? A plain breakdown", "cost to self-publish a book"),
            ("Books make great gifts: how to sell signed copies this season", "sell signed books"),
            ("12 books about writing every author should read", "best books on writing"),
            ("Our first three months: what authors taught us", "DREM Book"),
        ],
        "mon": [
            ("L", "CAR", "Your 2027 book plan in 5 steps"),
            ("L", "TIP", "What to budget for when you publish a book"),
            ("L", "CAR", "How long each publishing stage takes (timeline)"),
            ("L", "TIP", "5 year-end reflection prompts for writers"),
            ("", "", ""),
        ],
        "fri": [
            ("O", "ANN", "Now booking January editing slots"),
            ("B", "REEL", "A cover from first sketch to final design"),
            ("B", "ANN", "Holiday hours and response times"),
            ("D", "ANN", "Merry Christmas from DREM Book"),
            ("", "", ""),
        ],
        "sun": [
            ("C", "POLL", "What's your writing goal for 2027?"),
            ("C", "CAR", "Gift guide: presents for the writer in your life"),
            ("D", "QUO", "Every book starts as a dream (brand tagline quote)"),
            ("C", "POLL", "Share your 2026 writing win, big or small"),
            ("", "", ""),
        ],
    },
    "2027-01": {
        "theme": "New year, new book",
        "summary": "Goal season. Turn New Year energy into a 12-month plan, and invite discovery calls.",
        "campaign": "\"Finish your book in 2027\" series; New Year manuscript assessment offer",
        "newsletter": "The 12-month plan to finish your book in 2027",
        "blogs": [
            ("How to finally finish your book in 2027: a 12-month plan", "how to finish writing a book"),
            ("Writing habits that stick: the small-daily method", "writing habits"),
            ("Nonfiction authors: how to outline a book from your expertise", "how to outline a nonfiction book"),
            ("Memoir 101: how to start writing your life story", "how to write a memoir"),
            ("", ""),
        ],
        "mon": [
            ("L", "CAR", "The 12-month book plan"),
            ("L", "TIP", "Set a word-count goal you'll actually keep"),
            ("L", "CAR", "Nonfiction book outline template"),
            ("L", "TIP", "Memoir: 5 memories worth writing first"),
            ("", "", ""),
        ],
        "fri": [
            ("D", "ANN", "Happy New Year: every book starts as a dream"),
            ("O", "SVC", "New Year manuscript assessment: find out what your draft needs"),
            ("B", "REEL", "How we match you with the right editor"),
            ("O", "SVC", "Editing: developmental, line and copyediting (refresh)"),
            ("B", "CAR", "A book's journey with DREM Book, start to finish"),
        ],
        "sun": [
            ("C", "POLL", "Describe your book in one sentence"),
            ("C", "POLL", "Fiction or nonfiction: what are you writing this year?"),
            ("D", "QUO", "Louis L'Amour: \"Start writing, no matter what. The water does not flow until the faucet is turned on.\""),
            ("C", "PHOTO", "Show us your writing corner in 2027"),
            ("C", "POLL", "January win thread: share one thing you finished"),
        ],
    },
    "2027-02": {
        "theme": "Love your story",
        "summary": "Craft month: characters, voice and romance, plus Black History Month (US and Canada).",
        "campaign": "Character week; Black History Month reading list",
        "newsletter": "Characters readers can't forget + a free character questionnaire",
        "blogs": [
            ("How to create characters readers can't forget", "how to create characters"),
            ("Finding your writing voice: 6 exercises", "how to find your writing voice"),
            ("Writing romance: tropes readers love and how to make them fresh", "romance tropes"),
            ("Black History Month: 10 Black authors every writer should read", "black authors to read"),
            ("", ""),
        ],
        "mon": [
            ("L", "CAR", "Character questionnaire (save this)"),
            ("L", "TIP", "3 quick fixes for flat dialogue"),
            ("L", "CAR", "First person or third? Point of view explained"),
            ("L", "CAR", "Romance tropes readers love"),
            ("", "", ""),
        ],
        "fri": [
            ("O", "SVC", "Cover design for your genre (romance, thriller, memoir)"),
            ("O", "ANN", "Valentine's idea: gift a writer a manuscript assessment"),
            ("B", "REEL", "How we design a chapter opener"),
            ("O", "SVC", "Ebook & audiobook editions (refresh)"),
            ("", "", ""),
        ],
        "sun": [
            ("D", "QUO", "\"Until the lions have their own historians, the history of the hunt will always glorify the hunter.\" (African proverb shared by Chinua Achebe)"),
            ("C", "POLL", "Who is your favourite fictional couple?"),
            ("C", "POLL", "Pen and paper or keyboard?"),
            ("C", "POLL", "February win thread"),
            ("", "", ""),
        ],
    },
    "2027-03": {
        "theme": "Revise & edit",
        "summary": "Editing month, plus Women's History Month, World Book Day (UK) and World Poetry Day.",
        "campaign": "Self-editing challenge; spring editing slots",
        "newsletter": "The self-editing checklist: 25 fixes before you hire an editor",
        "blogs": [
            ("The self-editing checklist: 25 things to fix before you hire an editor", "self-editing checklist"),
            ("How to take editorial feedback without losing heart", "how to take editing feedback"),
            ("Beta readers vs editors: who to use and when", "beta readers vs editors"),
            ("Women who write: 10 women authors who shaped literature", "women authors"),
            ("Common grammar slips that sneak into manuscripts", "common grammar mistakes in writing"),
        ],
        "mon": [
            ("L", "CAR", "The self-editing checklist"),
            ("L", "TIP", "10 filler words to cut from your manuscript"),
            ("L", "REEL", "Why reading your book aloud catches mistakes"),
            ("L", "TIP", "5 questions to ask your beta readers"),
            ("L", "CAR", "One sentence, three edits: before and after"),
        ],
        "fri": [
            ("O", "SVC", "Developmental editing: fixing the big picture"),
            ("D", "CAR", "Women authors we admire (Women's History Month)"),
            ("B", "CAR", "What an editorial letter looks like"),
            ("O", "ANN", "Now booking spring editing slots"),
            ("", "", ""),
        ],
        "sun": [
            ("D", "QUO", "A line from a woman author you love (Mothering Sunday UK)"),
            ("C", "POLL", "How many drafts did your book take?"),
            ("C", "POLL", "World Poetry Day: share a line of poetry you love"),
            ("C", "POLL", "March win thread"),
            ("", "", ""),
        ],
    },
    "2027-04": {
        "theme": "Design your book",
        "summary": "Covers, interiors and blurbs, with National Poetry Month (US and Canada) and World Book Day (Apr 23).",
        "campaign": "Cover week (A/B cover polls); design package offer",
        "newsletter": "What makes a great cover, by genre",
        "blogs": [
            ("What makes a great book cover? 7 principles by genre", "book cover design tips"),
            ("Trim sizes explained: choosing the right size for your book", "book trim sizes"),
            ("How to write a back-cover blurb that sells", "how to write a book blurb"),
            ("Children's picture books: how words and pictures work together", "how to make a children's picture book"),
            ("", ""),
        ],
        "mon": [
            ("L", "CAR", "Cover cues by genre: what readers expect"),
            ("L", "TIP", "Trim sizes: which fits your book?"),
            ("L", "CAR", "The back-cover blurb formula"),
            ("L", "TIP", "Fonts that read well in print"),
            ("", "", ""),
        ],
        "fri": [
            ("O", "SVC", "International Children's Book Day: children's book design and printing"),
            ("B", "REEL", "Cover concept to final file"),
            ("O", "SVC", "Interior formatting for print and ebook"),
            ("C", "POLL", "World Book Day: which book made you a reader?"),
            ("O", "ANN", "Design package: cover + interior"),
        ],
        "sun": [
            ("C", "POLL", "Cover A or cover B? (vote)"),
            ("C", "POLL", "Poetry Month: share a poem that moved you"),
            ("D", "QUO", "Quote about books and reading (public-domain author)"),
            ("C", "POLL", "April win thread"),
            ("", "", ""),
        ],
    },
    "2027-05": {
        "theme": "Self-publishing 101",
        "summary": "The practical side: ISBNs, formats, printing, distribution and copyright.",
        "campaign": "\"Publish by summer\" package",
        "newsletter": "Self-publishing jargon, decoded",
        "blogs": [
            ("ISBNs explained: what they are, who issues them and how many you need", "what is an ISBN"),
            ("Paperback or hardcover: which should you print?", "paperback vs hardcover"),
            ("Print-on-demand vs offset printing: pros and cons", "print on demand vs offset printing"),
            ("How book distribution works: retailers, libraries and your own shop", "book distribution for self-published authors"),
            ("", ""),
        ],
        "mon": [
            ("L", "CAR", "ISBNs by country: US, UK, Canada and Nigeria"),
            ("L", "CAR", "Book formats compared"),
            ("L", "TIP", "Print-on-demand or offset?"),
            ("L", "CAR", "Where readers buy books"),
            ("L", "TIP", "Categories and keywords: how readers find your book"),
        ],
        "fri": [
            ("O", "SVC", "Printing: paperback and hardcover (refresh)"),
            ("B", "REEL", "Unboxing a proof copy"),
            ("O", "SVC", "Distribution: getting your book to readers"),
            ("O", "ANN", "Publish by summer: book your slot"),
            ("", "", ""),
        ],
        "sun": [
            ("C", "POLL", "What book did someone read to you as a child?"),
            ("C", "POLL", "Mother's Day (US): books our mothers loved"),
            ("C", "POLL", "What's one publishing question you've always had?"),
            ("D", "QUO", "Every finished book was once a messy draft"),
            ("C", "POLL", "May win thread"),
        ],
    },
    "2027-06": {
        "theme": "Read, swipe, listen",
        "summary": "Audiobook Month and digital editions, plus a mid-year check-in.",
        "campaign": "Audiobook Month; add-an-audiobook offer",
        "newsletter": "Is an audiobook right for your book?",
        "blogs": [
            ("Is an audiobook right for your book?", "should I make an audiobook"),
            ("How audiobooks are made: from script to studio", "how are audiobooks made"),
            ("Ebook formatting: what changes from print", "ebook formatting"),
            ("Reaching readers in Africa, Europe and North America with digital editions", "sell ebooks internationally"),
            ("Mid-year check-in: is your book on track?", "writing goals"),
        ],
        "mon": [
            ("L", "CAR", "Author-narrated or professional narrator?"),
            ("L", "TIP", "Print vs ebook formatting: what changes"),
            ("L", "TIP", "How long will your audiobook be? (about 9,000 words per hour)"),
            ("L", "CAR", "Mid-year goal reset"),
            ("", "", ""),
        ],
        "fri": [
            ("O", "SVC", "Ebook & audiobook: read it, swipe it, hear it"),
            ("B", "REEL", "Inside an audiobook recording session"),
            ("C", "POLL", "Father's Day: books our fathers loved"),
            ("O", "ANN", "Add an audiobook to your book"),
            ("", "", ""),
        ],
        "sun": [
            ("C", "POLL", "Do you read, listen, or both?"),
            ("C", "POLL", "What's the best audiobook you've heard?"),
            ("D", "QUO", "Quote about stories and listening"),
            ("C", "POLL", "Halfway through 2027: how's your book going?"),
            ("", "", ""),
        ],
    },
    "2027-07": {
        "theme": "Finish & polish",
        "summary": "Phase 3 starts. Open the holiday-launch campaign with a real production deadline.",
        "campaign": "\"Publish before the holidays\" campaign opens",
        "newsletter": "Want your book out for the holidays? Here's the deadline",
        "blogs": [
            ("Want your book out for the holidays? Your deadline calendar", "publish a book before christmas"),
            ("Summer writing: how to keep going when life is busy", "summer writing routine"),
            ("How to write an author bio", "how to write an author bio"),
            ("Author photos: tips for a professional headshot", "author headshot tips"),
            ("", ""),
        ],
        "mon": [
            ("L", "CAR", "Holiday-launch countdown timeline"),
            ("L", "TIP", "Author bio formula"),
            ("L", "TIP", "A summer writing routine that fits real life"),
            ("L", "CAR", "Headshot tips for authors"),
            ("", "", ""),
        ],
        "fri": [
            ("O", "ANN", "Publish before the holidays: campaign opens (state the deadline)"),
            ("B", "REEL", "A book's journey in 60 seconds"),
            ("O", "SVC", "Full publishing package: edit, design, print, distribute"),
            ("B", "CAR", "Client story (with written permission)"),
            ("O", "ANN", "Holiday-launch reminder: slots and deadline"),
        ],
        "sun": [
            ("C", "POLL", "Where do you read in summer?"),
            ("C", "POLL", "What are you reading this month?"),
            ("D", "QUO", "Dream it. Write it. Hold it. (brand tagline)"),
            ("C", "POLL", "July win thread"),
            ("", "", ""),
        ],
    },
    "2027-08": {
        "theme": "Launch your book",
        "summary": "Marketing basics for authors, and the last full month for holiday launches.",
        "campaign": "Holiday-launch campaign, final month; Book Lovers Day",
        "newsletter": "Plan your book launch in 8 weeks",
        "blogs": [
            ("How to plan a book launch in 8 weeks", "how to launch a book"),
            ("Building an author platform before you publish", "author platform"),
            ("How to get book reviews the right way", "how to get book reviews"),
            ("Book launch events: bookshops, libraries and online", "book launch event ideas"),
            ("Email newsletters for authors: a starter guide", "author newsletter"),
        ],
        "mon": [
            ("L", "CAR", "The 8-week launch plan"),
            ("C", "POLL", "Book Lovers Day: what book do you recommend to everyone?"),
            ("L", "CAR", "Author platform checklist"),
            ("L", "TIP", "Launch-day checklist"),
            ("L", "TIP", "Newsletter basics for authors"),
        ],
        "fri": [
            ("O", "ANN", "Holiday launch: last month to book"),
            ("B", "CAR", "Client story (with written permission)"),
            ("B", "REEL", "Packing author copies for a launch event"),
            ("O", "SVC", "Printing: author copies for events and signings"),
            ("", "", ""),
        ],
        "sun": [
            ("O", "SVC", "Launch-ready package: edit, design and print by the deadline"),
            ("C", "POLL", "Would you rather launch online or in a bookshop?"),
            ("D", "QUO", "Quote about perseverance in writing"),
            ("C", "POLL", "August win thread"),
            ("O", "ANN", "Last call for holiday launches: what's stopping you? (answer objections in stories)"),
        ],
    },
    "2027-09": {
        "theme": "Back to your book",
        "summary": "Autumn restart, International Literacy Day, and final call for holiday launches.",
        "campaign": "Final call: publish before the holidays",
        "newsletter": "Your autumn writing plan + final holiday-launch dates",
        "blogs": [
            ("Back to school, back to your book: an autumn writing plan", "writing routine"),
            ("International Literacy Day: why every story matters", "international literacy day"),
            ("Writing for young readers: middle grade and YA basics", "how to write young adult fiction"),
            ("Final checklist before you send your book to print", "book printing checklist"),
            ("", ""),
        ],
        "mon": [
            ("L", "CAR", "Autumn writing plan"),
            ("L", "TIP", "Middle grade vs YA: what's the difference?"),
            ("L", "CAR", "Pre-print checklist"),
            ("L", "TIP", "How to read a printer's proof"),
            ("", "", ""),
        ],
        "fri": [
            ("O", "ANN", "Final call: publish before the holidays"),
            ("D", "CAR", "International Literacy Day: why stories matter"),
            ("O", "SVC", "Proofreading: the final check before print"),
            ("O", "SVC", "Editing for young readers"),
            ("", "", ""),
        ],
        "sun": [
            ("C", "POLL", "Which book do you remember from school?"),
            ("C", "POLL", "What's your autumn writing goal?"),
            ("D", "QUO", "Quote about reading and freedom"),
            ("C", "POLL", "September win thread"),
            ("", "", ""),
        ],
    },
    "2027-10": {
        "theme": "One year of dreams",
        "summary": "DREM Book's first anniversary on Oct 1, UK Black History Month, and pre-order season.",
        "campaign": "Anniversary week (Oct 1–7); pre-order campaigns for holiday books",
        "newsletter": "One year of DREM Book: thank you, and what's next",
        "blogs": [
            ("One year of DREM Book: what we learned helping authors", "DREM Book"),
            ("How to build suspense: lessons from spooky stories", "how to build suspense in writing"),
            ("Black History Month (UK): Black British and African authors to read", "black british authors"),
            ("Pre-order campaigns: how to build buzz before launch", "book pre-order campaign"),
            ("", ""),
        ],
        "mon": [
            ("L", "CAR", "Our 10 best writing tips from year one"),
            ("L", "TIP", "5 ways to build suspense"),
            ("L", "CAR", "How to set up a pre-order"),
            ("L", "TIP", "What to post in the month before launch"),
            ("", "", ""),
        ],
        "fri": [
            ("D", "ANN", "Happy first birthday, DREM Book: thank you"),
            ("B", "CAR", "Year one in numbers (real figures only)"),
            ("O", "SVC", "Cover design for holiday books"),
            ("B", "CAR", "Client story (with written permission)"),
            ("C", "POLL", "Halloween: tell us a story in 6 words"),
        ],
        "sun": [
            ("O", "ANN", "Year-two thank-you offer for returning authors"),
            ("C", "POLL", "Canadian Thanksgiving: a book you're grateful for"),
            ("D", "QUO", "Quote from an African or Black British author"),
            ("C", "POLL", "October win thread"),
            ("C", "POLL", "Halloween reads: recommend a spooky book"),
        ],
    },
    "2027-11": {
        "theme": "Write & gift",
        "summary": "November writing month again, books as gifts, and the Black Friday / Cyber Monday offer.",
        "campaign": "30-day writing challenge (year two); Black Friday / Cyber Monday offer on 2028 slots",
        "newsletter": "Your November plan + early access to our Black Friday offer",
        "blogs": [
            ("November writing challenge: your 30-day plan", "november writing challenge"),
            ("Books as gifts: how authors can sell more in December", "sell books for christmas"),
            ("Signed copies and bundles: holiday ideas for authors", "author holiday promotion ideas"),
            ("How to write acknowledgements that matter", "how to write acknowledgements"),
            ("Small Business Saturday: why indie bookshops matter", "support indie bookshops"),
        ],
        "mon": [
            ("L", "TIP", "November word-count tracker (year two)"),
            ("L", "CAR", "Holiday selling ideas for authors"),
            ("L", "TIP", "How to price signed copies and bundles"),
            ("L", "TIP", "Acknowledgements: who to thank and how"),
            ("O", "ANN", "Cyber Monday: last day of the offer"),
        ],
        "fri": [
            ("B", "PHOTO", "Meet the team (year two)"),
            ("B", "REEL", "How we wrap and ship author copies"),
            ("O", "ANN", "Black Friday offer opens next week (early notice)"),
            ("O", "ANN", "Black Friday: 2028 booking offer"),
            ("", "", ""),
        ],
        "sun": [
            ("C", "POLL", "Which author changed your life? (Authors' Day week)"),
            ("C", "POLL", "Share your word count this week"),
            ("D", "QUO", "Quote about gratitude and stories"),
            ("C", "POLL", "What book are you giving as a gift this year?"),
            ("", "", ""),
        ],
    },
    "2027-12": {
        "theme": "Celebrate & plan 2028",
        "summary": "Year in review, gifts for writers, and planning 2028.",
        "campaign": "Year in review; book January 2028 slots",
        "newsletter": "2027 in review + your 2028 book plan",
        "blogs": [
            ("2027 in review: the books we helped bring to life", "DREM Book"),
            ("Plan your 2028 book: a step-by-step guide", "how to plan writing a book"),
            ("Gift guide for writers, 2027 edition", "gifts for writers"),
            ("The year's best writing advice in one post", "writing advice"),
            ("", ""),
        ],
        "mon": [
            ("L", "CAR", "Your 2028 book plan"),
            ("L", "TIP", "Year-end reflection prompts"),
            ("O", "CAR", "Gift guide for writers: give an editing or design voucher"),
            ("L", "CAR", "Our most-saved tips of 2027"),
            ("", "", ""),
        ],
        "fri": [
            ("B", "CAR", "2027 in review: books we helped make (with permission)"),
            ("O", "ANN", "Now booking January 2028"),
            ("B", "ANN", "Holiday hours and response times"),
            ("D", "ANN", "Merry Christmas from DREM Book"),
            ("D", "ANN", "Happy New Year: every book starts as a dream"),
        ],
        "sun": [
            ("C", "POLL", "What's your writing goal for 2028?"),
            ("C", "POLL", "Best book you read this year?"),
            ("D", "QUO", "Dream it. Write it. Hold it."),
            ("C", "POLL", "Share your 2027 writing win"),
            ("", "", ""),
        ],
    },
}

# Launch-day items that sit outside the weekly rhythm.
SPECIAL = [
    ("2026-10-01", "Social", "D", "ANN", "Launch: Every book starts as a dream (sample post 08)"),
    ("2026-10-01", "Blog", "D", "", "Every book starts as a dream: meet DREM Book"),
]

# Key dates: (date, event, regions, idea, confirm)
# confirm=True means the organiser sets the date each year: check before posting.
KEY_DATES = [
    ("2026-10-01", "Nigeria Independence Day", "Nigeria", "Launch day. Greet Nigerian followers alongside the launch post.", False),
    ("2026-10-01", "Black History Month begins (UK)", "UK", "Share Black British and African authors through October.", False),
    ("2026-10-10", "World Mental Health Day", "Worldwide", "Story: writing as care; be gentle with your draft.", False),
    ("2026-10-12", "Thanksgiving (Canada)", "Canada", "Story: a book you're grateful for.", False),
    ("2026-10-14", "Frankfurt Book Fair (mid-October)", "Europe", "Story: what book fairs are and why they matter to authors.", True),
    ("2026-10-16", "Dictionary Day (US)", "US", "Story: favourite word quiz.", False),
    ("2026-10-31", "Halloween", "US, Canada, UK", "Fun community post (scheduled Oct 30).", False),
    ("2026-11-01", "National Authors' Day (US) + November writing month", "US, Worldwide", "Kick off the 30-day writing challenge.", False),
    ("2026-11-15", "Lagos Book & Art Festival / Aké Festival season", "Nigeria", "Share if attending; celebrate Nigerian writers.", True),
    ("2026-11-26", "Thanksgiving (US)", "US", "Thank-you story; no sales push.", False),
    ("2026-11-27", "Black Friday", "US, UK, Canada, Nigeria", "Early booking offer for 2027 (Friday slot).", False),
    ("2026-11-28", "Small Business Saturday (US)", "US", "Story: shout out indie bookshops.", False),
    ("2026-11-30", "Cyber Monday", "US, UK, Canada", "Story: last day of early-booking offer.", False),
    ("2026-12-01", "Giving Tuesday", "US, Worldwide", "Story: support a literacy charity you believe in.", False),
    ("2026-12-25", "Christmas Day", "Worldwide", "Greeting (Friday slot).", False),
    ("2026-12-26", "Boxing Day", "UK, Canada, Nigeria", "Story: reading by the fire.", False),
    ("2027-01-01", "New Year's Day", "Worldwide", "Greeting (Friday slot).", False),
    ("2027-02-01", "Black History Month begins (US, Canada)", "US, Canada", "Reading list blog + Sunday quote.", False),
    ("2027-02-14", "Valentine's Day", "Worldwide", "Favourite fictional couple (Sunday slot).", False),
    ("2027-03-04", "World Book Day (UK & Ireland)", "UK", "Story: dress-up as a book character photos.", True),
    ("2027-03-07", "Mothering Sunday (UK)", "UK", "Sunday quote from a woman author.", False),
    ("2027-03-08", "International Women's Day", "Worldwide", "Women authors carousel (Friday Mar 12) + story on the day.", False),
    ("2027-03-10", "Eid al-Fitr (around Mar 9–10, moon-dependent)", "Nigeria, UK, Worldwide", "Eid Mubarak greeting.", True),
    ("2027-03-16", "London Book Fair (usually March)", "UK", "Story: book fair tips for authors.", True),
    ("2027-03-21", "World Poetry Day", "Worldwide", "Share a line of poetry (Sunday slot).", False),
    ("2027-03-28", "Easter Sunday", "Worldwide", "Short greeting story.", False),
    ("2027-04-01", "National Poetry Month begins (US, Canada)", "US, Canada", "Poetry prompts in stories all month.", False),
    ("2027-04-02", "International Children's Book Day", "Worldwide", "Children's book service (Friday slot).", False),
    ("2027-04-23", "World Book and Copyright Day", "Worldwide", "Which book made you a reader? (Friday slot).", False),
    ("2027-04-24", "Independent Bookstore Day (US)", "US", "Story: tag your favourite indie bookshop.", False),
    ("2027-05-09", "Mother's Day (US, Canada)", "US, Canada", "Books our mothers loved (Sunday slot).", False),
    ("2027-05-16", "Eid al-Adha (around May 16–17, moon-dependent)", "Nigeria, UK, Worldwide", "Eid greeting.", True),
    ("2027-05-27", "Children's Day (Nigeria)", "Nigeria", "Story: books every Nigerian child should read.", False),
    ("2027-06-01", "Audiobook Month", "US, Worldwide", "Audio theme all month.", False),
    ("2027-06-12", "Democracy Day (Nigeria)", "Nigeria", "Story: stories that shaped a nation.", False),
    ("2027-06-20", "Father's Day (US, UK, Canada)", "US, UK, Canada", "Books our fathers loved (Friday Jun 18).", False),
    ("2027-07-01", "Canada Day", "Canada", "Story: Canadian authors we love.", False),
    ("2027-07-04", "Independence Day (US)", "US", "Story: summer reading pick.", False),
    ("2027-08-09", "Book Lovers Day", "US, Worldwide", "Community post (Monday slot).", False),
    ("2027-08-14", "Edinburgh International Book Festival (August)", "UK", "Story: festival highlights.", True),
    ("2027-09-06", "Labor Day (US, Canada)", "US, Canada", "Story: a rest-day reading pick.", False),
    ("2027-09-08", "International Literacy Day", "Worldwide", "Literacy blog + Friday carousel.", False),
    ("2027-09-26", "Banned Books Week (late Sep / early Oct)", "US", "Story: the freedom to read.", True),
    ("2027-10-01", "DREM Book first anniversary + Nigeria Independence Day", "Nigeria, Worldwide", "Anniversary post (Friday slot).", False),
    ("2027-10-11", "Thanksgiving (Canada)", "Canada", "A book you're grateful for (Sunday Oct 10).", False),
    ("2027-10-13", "Frankfurt Book Fair (mid-October)", "Europe", "Story: rights and translations basics.", True),
    ("2027-10-31", "Halloween", "US, Canada, UK", "Spooky reads (Sunday slot).", False),
    ("2027-11-01", "National Authors' Day (US) + November writing month", "US, Worldwide", "Kick off year-two writing challenge.", False),
    ("2027-11-25", "Thanksgiving (US)", "US", "Thank-you story; no sales push.", False),
    ("2027-11-26", "Black Friday", "US, UK, Canada, Nigeria", "2028 booking offer (Friday slot).", False),
    ("2027-11-27", "Small Business Saturday (US)", "US", "Blog + story: indie bookshops.", False),
    ("2027-11-29", "Cyber Monday", "US, UK, Canada", "Last day of the offer (Monday slot).", False),
    ("2027-11-30", "Giving Tuesday", "US, Worldwide", "Story: a literacy charity.", False),
    ("2027-12-25", "Christmas Day", "Worldwide", "Greeting (Friday Dec 24).", False),
    ("2027-12-26", "Boxing Day", "UK, Canada, Nigeria", "Story: reading pick.", False),
]

# Which platforms each weekly slot goes to.
PLATFORMS = {
    "mon": "Instagram (carousel), LinkedIn (PDF carousel), Facebook, Threads, Pinterest",
    "wed": "Instagram, Facebook, LinkedIn, X, Pinterest (pin links to the blog)",
    "fri": "Instagram, Facebook, LinkedIn, X, WhatsApp Status",
    "sun": "Instagram, Facebook, Threads, X, WhatsApp Status",
    "video": "Instagram Reels, TikTok, YouTube Shorts, Facebook Reels",
    "blog": "Website blog; shared to LinkedIn and Pinterest the same day",
    "newsletter": "Email newsletter",
    "key": "Instagram & Facebook Stories, WhatsApp Status (quick, light-effort)",
}
